### ISSUE TITLE
Problems installing merross add-on

### ISSUE THREAD

**Issue by rgutialo** [vincenzosuraci/hassio_meross_sensor_switch#15]
Hi all,

I'm trying to install this add-on into my raspberry pi 2. (hassio v0.97.2)
I've done everything as you said but nothing happens. I mean:

- I created /config/custom_components/meross
- I copied all *.py files and manifest.json files (total: 4 files)
- I changed configuration.yaml as you said....

And nothing happens. How do I know that meross_iot was downloaded?.
How do i know that all previous steps was succesfully done?.

Thanks in advance and congratulations for this project!

**Comment by rgutialo** [comment]
This is the error I get in logs:

`Error loading custom_components.meross. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 355, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/meross/__init__.py", line 8, in <module>
    from meross_iot.cloud.exceptions.CommandTimeoutException import CommandTimeoutException
ModuleNotFoundError: No module named 'meross_iot'`

**Comment by atzbert** [comment]
same here...

**Comment by RuBiCK** [comment]
I had the same issue. Solved following the instructions:
First install, reboot and then config. Maybe you are copying the files, configuring and then rebooting. 
Try to follow the order.
I solved the issue the now I don't know where should appear information of meross

**Comment by vincenzosuraci** [comment]
Dear all, I sugget to move on this component : [Alberto Geniola](https://github.com/albertogeniola/meross-homeassistant)
