### ISSUE TITLE
File "/config/custom_components/meross/__init__.py", line 275, in async_discover_plugs 

### ISSUE THREAD

**Issue by RuBiCK** [vincenzosuraci/hassio_meross_sensor_switch#17]
I'm trying to configure the plugin but I get the following error:

```
2019-09-22 23:55:03 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/meross/__init__.py", line 275, in async_discover_plugs
    meross_plugs = self._meross_manager.get_devices_by_kind(GenericPlug)
2019-09-22 23:55:03 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/meross/__init__.py", line 275, in async_discover_plugs
    meross_plugs = self._meross_manager.get_devices_by_kind(GenericPlug)
AttributeError: 'NoneType' object has no attribute 'get_devices_by_kind'
```

Any clue about what could be happening?

**Comment by vincenzosuraci** [comment]
Hi, I sugget to move on this component : [Alberto Geniola](https://github.com/albertogeniola/meross-homeassistant)
