### ISSUE TITLE
Error with mss310 (HW version 2.0.0 firmware version 2.1.5)

### ISSUE THREAD

**Issue by Klagio** [vincenzosuraci/hassio_meross_sensor_switch#2]
```
meross:
  username: !secret meross_email
  password: !secret meross_password
  scan_interval: 10

```

2019-04-09 21:57:09 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140322101615192] 'GenericPlug' object has no attribute 'device'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 122, in handle_call_service
    connection.context(msg))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1138, in async_call
    self._execute_service(handler, service_call))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1160, in _execute_service
    await handler.func(service_call)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 188, in handle_service
    self._platforms.values(), func, call, service_name
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 314, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 328, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/meross/switch.py", line 60, in turn_on
    device.device.turn_on_channel(self.channel)
AttributeError: 'GenericPlug' object has no attribute 'device'
2019-04-09 21:57:10 ERROR (MainThread) [homeassistant.components.automation] Error while executing automation automation.sensor_values_to_file. Unknown error for call_service at pos 1: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/automation/__init__.py", line 380, in action
    await script_obj.async_run(variables, context)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/script.py", line 131, in async_run
    await self._handle_action(action, variables, context)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/script.py", line 210, in _handle_action
    action, variables, context)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/script.py", line 299, in _async_call_service
    context=context
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 88, in async_call_from_config
    domain, service_name, service_data, blocking=blocking, context=context)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1138, in async_call
    self._execute_service(handler, service_call))
  File "/usr/local/lib/python3.7/site-packages/homeassistant/core.py", line 1160, in _execute_service
    await handler.func(service_call)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/notify/__init__.py", line 117, in async_notify_message
    await notify_service.async_send_message(**kwargs)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/file/notify.py", line 47, in send_message
    with open(self.filepath, 'a') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/share/history/10sec_power_reading.csv'
2019-04-09 21:57:10 ERROR (MainThread) [homeassistant.components.automation] Error while executing automation automation.automation_ran. Service not found for call_service at pos 2: (ServiceNotFound(...), 'Service notify.filed_automations not found')
2019-04-09 21:57:10 ERROR (MainThread) [homeassistant.components.automation] Error while executing automation automation.automation_ran. Service not found for call_service at pos 2: (ServiceNotFound(...), 'Service notify.filed_automations not found')
2019-04-09 21:57:19 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140322101615192] 'GenericPlug' object has no attribute 'device'
Traceback (most recent call last):

**Comment by Klagio** [comment]
sensor values seems fine, but the switch does not turn on. When using meross app, turning on does not follow in hass

**Comment by Klagio** [comment]
the Meross app suggest to upgrade the firmware, shall I?

**Comment by vincenzosuraci** [comment]
Dear Klagio,
many thanks for your log reporting, it helped to find a typo in File "/config/custom_components/meross/switch.py", line 60. 

I corrected it with the last commit. Let me know if it works.

VS

P.S.: I suggest you to always upgrade your devices to the latest firmware officially released by the device manifacturers.

**Comment by vincenzosuraci** [comment]
Dear Klagio,
Regarding this:
> sensor values seems fine, but the switch does not turn on. When using meross app, turning on does not follow in hass

take into account that when you use different way to control Meross devices (e.g. iPhone app + HA) there will always be a synchronization delay between them. It is due to how all these devices work. They all communicate with a centralized Meross server, so, depending on how frequently they query the server, the less this synchronization delay will be.

**Comment by vincenzosuraci** [comment]
Dear Klagio,
I kindly ask to you to download and test the latest version and let me know if it hangs out.

VS

**Comment by vincenzosuraci** [comment]
Dear Klagio,
Let me know if you have the chance to test the latest version of the custom component. From our tests it is working stably. I you feedback me, I can close this issue.

**Comment by vincenzosuraci** [comment]
Dear Klagio,
I'm going to close this issue. Right now we are testing the reliability of the custom-component when operating for a long time.

VS

**Comment by Klagio** [comment]
sorry for absence, updated the component now, seems to work fine
