### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by jayjaytyper** [vincenzosuraci/hassio_meross_sensor_switch#6]
Mon Apr 22 2019 08:02:42 GMT+0100 (British Summer Time)
Error loading custom_components.meross. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 183, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/meross/__init__.py", line 18, in <module>
    from meross_iot.supported_devices.power_plugs import (GenericPlug, ClientStatus)
ImportError: cannot import name 'GenericPlug' from 'meross_iot.supported_devices.power_plugs' (/config/deps/lib/python3.7/site-packages/meross_iot/supported_devices/power_plugs.py)

**Comment by jasonrussell70** [comment]
Hello, When i try and use this i get the error above.

**Comment by jayjaytyper** [comment]
Sorry i closed the wrong one

**Comment by vincenzosuraci** [comment]
Hi @jayjaytyper ,
it seems you have problem with the dependencies. I do not know why are you getting this error, since, if you carefully read it:

    ImportError: cannot import name 'GenericPlug' from 'meross_iot.supported_devices.power_plugs' (/config/deps/lib/python3.7/site-packages/meross_iot/supported_devices/power_plugs.py)

it is clear that the system does not find the 'GenericPlug' class, that should be located in 'meross_iot.supported_devices.power_plugs'. I guess something wrong went during the installation of the dependency.

Possible solutions are:
1. if you are not using Hassio, you have to manually add the dependency (e.g. read [here](https://github.com/albertogeniola/MerossIot#installation))
2. if you are using Hassio, the dependency should have been automatically installed, but something went wrong. So, try to copy the actual files (that you can download [here](https://github.com/albertogeniola/MerossIot/tree/master/meross_iot)) and overwrite the ones that are in '/config/deps/lib/python3.7/site-packages/meross_iot' folder.

I hope this helps you.

VS

**Comment by jayjaytyper** [comment]
Hi @vincenzosuraci, 

I was using Hassio and a manual copy of the files did the trick. thank you for you support.

Regards
